
//#undef _UNICODE

#include <stdio.h>
#include <utility>

#include <tchar.h>
#include "header.h"
#include "header.h"
#include <windows.h>
#include <math.h>

#include <assert.h>

int main() 
{
	char input2[] = "50263290575266: Cccustom, CORE 6, Event generated by PID 1017, TID 41\n";
	char input[] = "50263290575266: Custom, CORE 6, Event generated by PID 1017, TID 41\n"
		"Kind : 100, Size : 4 bytes\n"
		"0x00000000 : 70 6C 63 30\n"
		"50263290623608 : SRI to Windows, CORE 6, Event generated by PID 1017, TID 41";

	int a;
	int ResultGet = sscanf( input, "%*d: Custom, CORE %*d, Event generated by PID %*d, TID %d\n", &a );

	return 0;
}

